### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by JulianWDev** [christosk92/Wavee#6]
Hi @christosk92 I've been following this project and it looks super interesting. Did notice that in your screenshots the app doesn't have one yet so took the liberty of drafting something in Illustrator. It's a bit rough but let me know if you like it or if you have some ideas.

![Wavee](https://github.com/christosk92/Wavee/assets/114243649/c917deb2-90b9-4a36-933b-5e8818807697)

Taking inspiration from the name (Wavee ~ waves) and some legally distinct but vaguely inspired by spotify squiggles.

Cheers, Julian

**Comment by christosk92** [comment]
Hi Julia,

Thanks so much for your interest in the project.

That logo you made looks sick! I've been thinking about it a couple of times, and I was actually thinking of something similar. Slightly different though. 
Well actually I want the logo to follow the Windows 11 fluent design style. Similar to how the office apps look.

I really **like** the idea of a plain Sine wave instead of an actual audio wave you'd see in an equalizer.

I did want a wave in the logo, maybe if the wave is a bit larger.
So following all the principles listed above, I suppose it'd be similar to this image I found on shutterstock (see below)

There's a couple of things I do not like about the Shutterstock image, mainly the colors, glows and the lack of a frame or background.
But I guess the core would look something like that.

Hit me up (maybe a portfolio?) if you're willing to draw something like that. Of course I'll be willing to pay a price, which we can discuss.

![image](https://github.com/christosk92/Wavee/assets/13438702/bde5d178-b8f2-431b-942a-5ac9db33693a)

**Comment by Reallukeisbest** [comment]
Hello, @christosk92!

I'm not a graphic designer but I really see potential in this project and, to provide a starting point, I've recreated the shutterstock in Figma (see svg below). Obviously, I'd expect this logo to be edited (as to avoid copyright infringement), although this could be a good start 🙂

![Frame 1](https://github.com/christosk92/Wavee/assets/58954397/6b8d807d-f44c-4bdf-854a-0533af3ae159)

Thank you,
- Luke
